package fp4g.generator;

import java.io.File;
import java.io.IOException;
import java.util.Map.Entry;

import com.apollo.managers.GameManager;
import com.apollo.managers.graphics.Sprite;
import com.apollo.managers.graphics.SpriteLoader;
import com.badlogic.gdx.assets.AssetManager;
import com.badlogic.gdx.assets.loaders.resolvers.InternalFileHandleResolver;
import com.sun.codemodel.JBlock;
import com.sun.codemodel.JClass;
import com.sun.codemodel.JClassAlreadyExistsException;
import com.sun.codemodel.JCodeModel;
import com.sun.codemodel.JDefinedClass;
import com.sun.codemodel.JExpr;
import com.sun.codemodel.JExpression;
import com.sun.codemodel.JFieldVar;
import com.sun.codemodel.JMethod;
import com.sun.codemodel.JMod;
import com.sun.codemodel.JPackage;
import com.sun.codemodel.JType;

import static fp4g.Log.ErrType;
import static fp4g.Log.WarnType;
import static fp4g.Log.InfoType;
import static fp4g.Log.Show;
import fp4g.data.Add;
import fp4g.data.Define;
import fp4g.data.IScope;
import fp4g.data.Start;
import fp4g.data.Type;

public class Generator
{
  private final JCodeModel jcm = Utils.getJCM();
  private IScope game;
  
  public Generator(IScope _game)
  {
    this.game = _game;
  } 
  
  public void generate(String outDirName)
    throws JClassAlreadyExistsException, IOException, ClassNotFoundException
  {
    String name = (String)this.game.get("name");
    int width = ((Integer)this.game.get("width")).intValue();
    int height = ((Integer)this.game.get("height")).intValue();
    
    JPackage gamePack = Utils.getGamePackage();
    JDefinedClass gameClass = gamePack._class(name);
    gameClass._extends(GameManager.class);
    
    Utils.addAutogenerated(gameClass);
    
    gameClass.field(25, this.jcm.INT, "Width", JExpr.lit(width));
    gameClass.field(25, this.jcm.INT, "Height", JExpr.lit(height));
    JFieldVar assetManagerVar = gameClass.field(20, AssetManager.class, "assetManager");
    JFieldVar fileResolverVar = gameClass.field(4, InternalFileHandleResolver.class, "fileResolver");
    
    JMethod createMethod = gameClass.method(1, this.jcm.VOID, "create");
    JBlock createBlock = createMethod.body();
    createMethod.annotate(Override.class);
    
    JMethod disposeMethod = gameClass.method(1, this.jcm.VOID, "dispose");
    JBlock disposeBlock = disposeMethod.body();
    disposeMethod.annotate(Override.class);
    
    disposeBlock.invoke(assetManagerVar, "dispose");
    disposeBlock.add(JExpr._super().invoke("dispose"));
    
    createBlock.assign(fileResolverVar, JExpr._new(this.jcm.ref(InternalFileHandleResolver.class)));
    createBlock.assign(assetManagerVar, JExpr._new(this.jcm.ref(AssetManager.class)));
    createBlock.add(assetManagerVar.invoke("setLoader").arg(this.jcm.ref(Sprite.class).staticRef("class")).arg(JExpr._new(this.jcm.ref(SpriteLoader.class)).arg(fileResolverVar)));
    
    
    for (Entry<String, Object> entry : game.toArray())
    {
      String key = String.format("_%s", entry.getKey());
      Object value = entry.getValue();
      
      if ((!key.equalsIgnoreCase("_name")) && (!key.equalsIgnoreCase("_width")) && (!key.equalsIgnoreCase("_height")))
      {
        JType typeValue = Utils.getType(value);
        JExpression expr = Utils.getExpr(value);
        if (expr != null)
        {
          gameClass.field(4, typeValue, key, expr);
        }
        else if ((value instanceof Define))
        {
          Define define = (Define)value;
          Type stateType = define.getType();
          if (stateType == Type.STATE)
          {
            StateGenerator sg = new StateGenerator(define);
            JDefinedClass state = sg.generate();
            JFieldVar var = gameClass.field(4, state, key, expr);
            
            createBlock.assign(var, JExpr._new(state));
          }
          
        }
        else if ((value instanceof Add))
        {
        	Add add = (Add)value;        	
			String addName = add.getName();
			//IScope addScope = add.getScope();
			Type addType = add.getType();
			Define addDefine = (Define) game.get(addName);
			if(addDefine == null)
			{
				//no está definido, se asume que existe				
				Show(WarnType.CustomAddState,add);
			}
			else
			{
				//No se esperaba esta combinación
				Show(WarnType.NotExpectedThis,add);
				Show(WarnType.NotExpectedThis,addDefine);				
								
			}
			switch(addType)
			{
			case STATE:
				JClass state = jcm.ref(String.format("%s.%s",gamePack.name(),addName));				
				JFieldVar var = gameClass.field(JMod.PRIVATE, state, String.format("_%s",addName));	            
	            createBlock.assign(var, JExpr._new(state));
				break;
				default:
					Show(ErrType.NotExpectedType,add);					
			}
			
        	
        }
        else if ((value instanceof Start))
        {
          Start start = (Start)value;
          createBlock.directStatement(String.format("start(_%s);",  start.getStartName()));
        } 
      } 
    } 
    
    gameClass.direct(
      "public static <T> T getAsset(String asset) {return assetManager.get(asset);}\n    public static <T> void loadAsset(String asset, Class<T> _class){assetManager.load(asset, _class);}\n    public static void unloadAsset(String asset){assetManager.unload(asset);}\n    public static void loadAssets() { assetManager.finishLoading();}");
    
    File outDir = new File(outDirName);
    if (!outDir.exists())
    {
      outDir.mkdirs();
    } 
    this.jcm.build(outDir);
    System.out.println("Generados en " + outDir.getAbsolutePath());
  } 
} 