package ${package};

<#if imports??>
<#list imports as import>
import import;
</#list>
</#if>

/**
  * AutoGenerated Class by FP4G
  ***DO NOT MODIFY***
  */
public class ${name} extends GameManager {
	public int Width  = ${width};
	public int Height = ${height};

	private AssetManager assetManager;
	private InternalFileHandleResolver fileResolver;

	@Override
	public void create()
	{
		fileResolver = new InternalFileHandleResolver();
		assetManager = new AssetManager();
		assetManager.setLoader(Sprite.class,new SpriteLoader(fileResolver));

		//iniciando el juego
    	<#if start_state??> 
		${start_state} _start = new ${start_state}(this);     	
		start(_start);
    	</#if>
	}
    
	@Override
	public void dispose()
	{
		super.dispose();
	}
    
	//funciones de utilidad  
	public static <T> T getAsset(String asset) {
		return assetManager.get(asset);
	}
	public static <T> void loadAsset(String asset, Class<T> clazz){
		assetManager.load(asset, clazz);
	}
	public static void unloadAsset(String asset){
		assetManager.unload(asset);
	}
	public static void loadAssets() { 
		assetManager.finishLoading();
	}
}