/* Generated By:JavaCC: Do not edit this line. FastPrototyping4GameConstants.java */
package fp4g.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FastPrototyping4GameConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int DEFINE = 7;
  /** RegularExpression Id. */
  int ADD = 8;
  /** RegularExpression Id. */
  int ON = 9;
  /** RegularExpression Id. */
  int SEND = 10;
  /** RegularExpression Id. */
  int GROUP = 11;
  /** RegularExpression Id. */
  int SUBSCRIBE = 12;
  /** RegularExpression Id. */
  int UNSUBSCRIBE = 13;
  /** RegularExpression Id. */
  int START = 14;
  /** RegularExpression Id. */
  int RESUME = 15;
  /** RegularExpression Id. */
  int PAUSE = 16;
  /** RegularExpression Id. */
  int EXIT = 17;
  /** RegularExpression Id. */
  int SYSTEM = 18;
  /** RegularExpression Id. */
  int GAME = 19;
  /** RegularExpression Id. */
  int STATE = 20;
  /** RegularExpression Id. */
  int BEHAVIOR = 21;
  /** RegularExpression Id. */
  int ENTITY = 22;
  /** RegularExpression Id. */
  int GOAL = 23;
  /** RegularExpression Id. */
  int MESSAGE = 24;
  /** RegularExpression Id. */
  int BASE = 25;
  /** RegularExpression Id. */
  int TO = 26;
  /** RegularExpression Id. */
  int SOURCE = 27;
  /** RegularExpression Id. */
  int ABRE_COR = 28;
  /** RegularExpression Id. */
  int ABRE_PAR = 29;
  /** RegularExpression Id. */
  int CIERRA_COR = 30;
  /** RegularExpression Id. */
  int CIERRA_PAR = 31;
  /** RegularExpression Id. */
  int COMA = 32;
  /** RegularExpression Id. */
  int EQUAL = 33;
  /** RegularExpression Id. */
  int DOT = 34;
  /** RegularExpression Id. */
  int INT_LITERAL = 35;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 36;
  /** RegularExpression Id. */
  int STRING_LITERAL = 37;
  /** RegularExpression Id. */
  int BOOL_LITERAL = 38;
  /** RegularExpression Id. */
  int DIGIT = 39;
  /** RegularExpression Id. */
  int PLUS = 40;
  /** RegularExpression Id. */
  int MINUS = 41;
  /** RegularExpression Id. */
  int MULTIPLY = 42;
  /** RegularExpression Id. */
  int DIVIDE = 43;
  /** RegularExpression Id. */
  int AND = 44;
  /** RegularExpression Id. */
  int OR = 45;
  /** RegularExpression Id. */
  int XOR = 46;
  /** RegularExpression Id. */
  int NOT = 47;
  /** RegularExpression Id. */
  int IDENTIFIER = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"DEFINE\"",
    "\"ADD\"",
    "\"ON\"",
    "\"SEND\"",
    "\"GROUP\"",
    "\"SUBSCRIBE\"",
    "\"UNSUBSCRIBE\"",
    "\"START\"",
    "\"RESUME\"",
    "\"PAUSE\"",
    "\"EXIT\"",
    "\"SYSTEM\"",
    "\"GAME\"",
    "\"STATE\"",
    "\"BEHAVIOR\"",
    "\"ENTITY\"",
    "\"GOAL\"",
    "\"MESSAGE\"",
    "\"BASE\"",
    "\"TO\"",
    "\"SOURCE\"",
    "\"[\"",
    "\"(\"",
    "\"]\"",
    "\")\"",
    "\",\"",
    "\"=\"",
    "\".\"",
    "<INT_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<STRING_LITERAL>",
    "<BOOL_LITERAL>",
    "<DIGIT>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"AND\"",
    "\"OR\"",
    "\"XOR\"",
    "\"NOT\"",
    "<IDENTIFIER>",
  };

}
